package com.swarmknowledge.osp

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/**
 * Cross-language vectors generated by the Python reference implementation
 * (mcp/osp_core.py) — the contract that makes a packet sealed in Python verify
 * in Kotlin and the same vectors mean the same thing on both sides.
 */
class InteropTest {

    private val t1 = "hydraulic pump failure is caused by cavitation and worn seals"
    private val t2 = "why does hydraulic pump failure happen"

    @Test
    fun embedMatchesPython256() {
        assertEquals(
            "0000000002040004000000000000000000000000010000020000080000000004",
            hex(embed(t1)),
        )
        assertEquals(
            "0000000002000004000000000000800000000000010000000000000000000000",
            hex(embed(t2)),
        )
    }

    @Test
    fun embedMatchesPython48ByteProfile() {
        // v0.5 Lite ships 48-byte vectors (dims 384); the dev embedder at dims 48
        // pins the same index math at a different width.
        assertEquals("000002040906", hex(embed(t1, dims = 48)))
    }

    @Test
    fun similarityMatchesPython() {
        assertEquals(0.375, similarity(embed(t1), embed(t2)), 1e-12)
        assertEquals(1.0, similarity(embed(t1), embed(t1)), 1e-12)
        assertEquals(0.0, similarity(ByteArray(0), embed(t1)), 1e-12)
    }

    @Test
    fun chunkHashMatchesPython() {
        assertEquals("sha256:1005aeaf4f76fe4d", chunkHash(t1))
    }

    @Test
    fun pythonSealedPacketVerifiesInKotlin() {
        val canonical = """{"action":"PROPOSE","exp_s":60,"gas":3,"jti":"j0123456789abcdef","origin_id":"pc-origin","packet_id":"pkt0123456789","payload":{"query_text":"why does hydraulic pump failure happen","query_vec":[0,0,0,0,2,0,0,4,0,0,0,0,0,0,128,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]},"query_id":"q123abc45678","sender":"pc-origin","trail":[{"action":"PROPOSE","node":"pc-origin"}],"ts":1758106059.123456,"v":"0.6"}"""
        val sig = "3c8e3ef54646bec01ec797dd174f1e344d6484ef22499c2da951526fc20a499a"

        val obj = MiniJson.parse(canonical) as Map<String, Any?>
        // canonical re-serialization must be byte-identical (sorted keys, float repr)
        assertEquals(canonical, MiniJson.write(obj))
        assertTrue(DevSigner().verify(obj, sig), "packet sealed by Python must verify here")

        // tampering breaks it (same legal shape, different content)
        val bad = obj.toMutableMap()
        bad["gas"] = 99L
        assertFalse(DevSigner().verify(bad, sig))
        assertNotEquals(sig, DevSigner().sign(bad))
    }

    @Test
    fun kotlinCanonicalOutputMatchesPythonBytes() {
        // The reverse direction: Kotlin signs the same logical object; its
        // canonical bytes must be exactly what Python json.dumps produces.
        val obj: Map<String, Any?> = linkedMapOf(
            "v" to "0.6", "packet_id" to "pkt0123456789", "jti" to "j0123456789abcdef",
            "ts" to 1758106059.123456, "exp_s" to 60L, "action" to "PROPOSE",
            "origin_id" to "pc-origin", "query_id" to "q123abc45678",
            "sender" to "pc-origin", "gas" to 3L,
            "trail" to listOf(mapOf("node" to "pc-origin", "action" to "PROPOSE")),
            "payload" to mapOf(
                "query_text" to t2,
                "query_vec" to byteArrayOf(0, 0, 0, 0, 2, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0x80.toByte(), 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
                    .map { it.toLong() and 0xFF },
            ),
        )
        val canonical = """{"action":"PROPOSE","exp_s":60,"gas":3,"jti":"j0123456789abcdef","origin_id":"pc-origin","packet_id":"pkt0123456789","payload":{"query_text":"why does hydraulic pump failure happen","query_vec":[0,0,0,0,2,0,0,4,0,0,0,0,0,0,128,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]},"query_id":"q123abc45678","sender":"pc-origin","trail":[{"action":"PROPOSE","node":"pc-origin"}],"ts":1758106059.123456,"v":"0.6"}"""
        assertEquals(canonical, MiniJson.write(obj))
        assertEquals(
            "3c8e3ef54646bec01ec797dd174f1e344d6484ef22499c2da951526fc20a499a",
            DevSigner().sign(obj),
        )
    }

    @Test
    fun doubleFormattingMatchesPythonRepr() {
        val samples = listOf(
            "1758106059.123456", "0.05", "0.688", "0.0001", "1e-05", "1e+16",
            "3.0", "0.15", "-42.5", "123456789.5", "0.001", "0.00025",
            "-0.0", "-1.234e-07", "-2.5e+16", "3465863721549106.0", "9999999999999998.0",
        )
        for (s in samples) assertEquals(s, MiniJson.pyDouble(s.toDouble()), "for input $s")
    }

    @Test
    fun queryCoverMatchesPythonGoldenValues() {
        // Same goldens as test_protocol.py / core.test.mjs: the symmetric
        // Jaccard collapses when chunk ≫ query (the third case scores 0.286
        // under Jaccard despite a perfect grounding), so retrieval competence
        // is query-side coverage, not Jaccard.
        val goldens = listOf(
            Triple("x y", "x z w v u", 0.5),
            Triple("bionics", "quantum pancake", 0.0),
            Triple("robot exosquelette", "<le robot humanoïde et l'exosquelette tactile>", 1.0),
            Triple("résumé document reçu", "résumé du document reçu hier", 1.0),
        )
        for ((q, c, cover) in goldens) {
            assertEquals(cover, queryCover(embed(q), embed(c)), 1e-12)
        }
    }

    @Test
    fun ragRetrieveRanksByQueryCover() {
        val chunk = "<le robot humanoïde et l'exosquelette tactile>"
        val rag = RagStore(listOf(chunk, "quantum pancake"))
        val hits = rag.retrieve(embed("robot exosquelette"))
        assertTrue(hits.isNotEmpty())
        assertEquals(1.0, hits[0].score, 1e-12)
        assertEquals(chunkHash(chunk), hits[0].chunk.hash)
    }
}
