// OSP v0.6 protocol core — pure Kotlin, zero third-party dependencies
// (the JVM equivalent of REQ-NF-01: kotlin-stdlib + JDK only).
//
// The module is a plain JVM library so that:
//   - unit tests run on the desktop JVM (fast, offline, deterministic — REQ-NF-03)
//   - the same JAR is consumable by harnessDroid and ospbridge (Android),
//     and by any JVM service.
// Wire format (canonical JSON + signatures) is interoperable with the Python
// reference implementation in ../mcp/osp_core.py — cross-language test vectors
// generated by that reference are embedded in the test suite.
plugins {
    kotlin("jvm")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
    }
}

dependencies {
    testImplementation(kotlin("test"))
}
